baseURL = "https://erstehilfekurs.co/"
languageCode = "de-de"
title = "Erste Hilfe Kurs"
theme = "hally"
googleAnalytics = "" # Add your identifier. For example UA-99631805-1.
paginate = 9

#-------------------------------
# Main Menu
[menu]
#  [[menu.main]]
#    identifier = "erfahrungen"
#    name = "Erfahrungen"
#    url = "/tags/review"
#    weight = 1

#  [[menu.main]]
#    identifier = "geschenke"
#    name = "Geschenkideen"
#    url = "/tags/gift/"
#    weight = 2

#  [[menu.main]]
#    identifier = "about"
#    name = "Über uns"
#    url = "/about"
#    weight = 3

  [[menu.main]]
    identifier = "kurs"
    name = "Online Kurs"
    url = "https://erste-hilfe-kurs-online.de/#aff=discount-applied&cam=nenu"
    weight = 1    

  [[menu.main]]
    identifier = "lifevac"
    name = "LifeVac"
    url = "https://deals.getlifevac.eu/LW9GMGR/2L7GN6P/?source_id=menu"
    weight = 2    

[params]
  logo = "" # You can add own logo. For example "/images/logo.png".
  description = "ErsteHilfeKurs.co ist Dein ultimativer Guide in der Welt der Ersten Hilfe, speziell für Kurse, Tipps und topaktuelle Gadgets! Wir sind für alle da, die ihr Erste-Hilfe-Wissen ausbauen oder sich mit den neuesten Hilfsmitteln ausstatten wollen. Egal, ob Du Dich auf Deinen nächsten Erste-Hilfe-Kurs vorbereitest oder das ideale Erste-Hilfe-Set suchst – hier bist Du richtig. Wir bieten Dir verlässliche Reviews, detaillierte Guides und die neuesten Infos rund um Erste Hilfe."

  #-------------------------------
  # Author Settings
  [params.author]
    author__name = "Erste Hilfe Kurs"
    author__image = "/logo.jpg"
    author__avatar = "/logo.jpg"
    author__description = "ErsteHilfeKurs.co ist Dein ultimativer Guide in der Welt der Ersten Hilfe, speziell für Kurse, Tipps und topaktuelle Gadgets! Wir sind für alle da, die ihr Erste-Hilfe-Wissen ausbauen oder sich mit den neuesten Hilfsmitteln ausstatten wollen. Egal, ob Du Dich auf Deinen nächsten Erste-Hilfe-Kurs vorbereitest oder das ideale Erste-Hilfe-Set suchst – hier bist Du richtig. Wir bieten Dir verlässliche Reviews, detaillierte Guides und die neuesten Infos rund um Erste Hilfe."

  #[[params.social]]
  #  icon = "ion-logo-twitter"
  #  name = "Twitter"
  #  link = "https://twitter.com"

  #[[params.social]]
  #  icon = "ion-logo-facebook"
  #  name = "Facebook"
  #  link = "https://www.facebook.com/gadgetadviserscom/"

  #[[params.social]]
  #  icon = "ion-logo-instagram"
  #  name = "Instagram"
  #  link = "https://www.instagram.com/gadgetadvisers/"

  #[[params.social]]
  #  icon = "ion-logo-youtube"
  #  name = "Youtube"
  #  link = "https://www.youtube.com/channel/UCrYEuUYxmGbx-aHOpqM6krg"

  # Other icons can be found at https://ionicons.com/v4/

  #-------------------------------
  # Newsletter (partials/footer-widgets/widget-subscribe.html)
  #[params.mailchimp]
  #  mailchimp__title = "Get Interesting News"
  #  mailchimp__text = "Subscribe to our newsletter and we’ll send you the emails of latest posts."
  #  mailchimp__identifier = "" # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
  #  mailchimp__button__text = "Subscribe" # Add your button text

  #-------------------------------
  # Contact Settings
  [params.contact]
    email = "info@roasperformance.com" # Add your email for contant form

    # NOTE
    # Hally comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

  #-------------------------------
  # Comment Section (Disqus)
  #[params.disqus]
  #  disqusShortname = "gadget-2" # add your shortname for Disqus Comment. For example anvod-studio-test

  [params.assets]
  custom_css = "css/custom.css"
  custom_js = "js/custom.js"  


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[outputs]
  home = ["HTML", "RSS", "JSON"]


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false